### ISSUE TITLE
citeproc-org won't find org-ref bibliography file when using hugo/ox-hugo with a main file and trying to export subtrees to markdown: `citeproc-org--get-link-bib-info: No bibliography file was specified`

### ISSUE THREAD

**Issue by lailamor** [andras-simonyi/citeproc-orgref#10]
# Description

When using hugo/ox-hugo, subtrees of single main org file that have org-ref citation(s) won't be exported to markdown files. Directory `blog/content/subtree` is created, but file won't be exported because citeproc-org won't find bibliography file.

<a id="orgc8c81bd"></a>

# Replication

1. Create hugo blog.
    
        hugo new site blog

2. Install theme.
    
        git init \
            && git submodule add --depth 1 \
                   https://github.com/reuixiy/hugo-theme-meme.git themes/meme \
            && rm config.toml \
            && cp themes/meme/config-examples/en/config.toml config.toml

3. Create main org file `blog/blog.org`. Add below to `blog.org`
<details>
  <summary>blog.org</summary>

  ```
  #+AUTHOR: Me

  #+STARTUP: content

  #+HUGO_BASE_DIR: .
  #+HUGO_AUTO_SET_LASTMOD: t


  * Posts                                                                :post:
    :PROPERTIES:
    :EXPORT_HUGO_SECTION: posts
    :END:

  ** Issue                                                             :@issue:

  *** DONE citeproc-org Won't Export org-ref in Single Main Org File :citeproc:org:
      CLOSED: [2020-09-14 Mon 02:08]
      :PROPERTIES:
      :EXPORT_DATE: 2020-09-14
      :EXPORT_FILE_NAME: citeproc-wont-reference-single-main-org-file
      :END:

      Lorem ipsum dolor sit amet, consectetuer adipiscing
      elit.cite:dominik-2010-tom7rm Donec hendrerit tempor tellus. Donec pretium
      posuere tellus. Proin quam nisl,[[cite:dominik-2010-tom7rm]] tincidunt et,
      mattis eget, convallis cite:dominik-2010-tom7rm nec, purus. Cum sociis
      natoque penatibus et magnis dis [[cite:dominik-2010-tom7rm]] parturient
      montes, nascetur ridiculus mus. Nulla posuere. Donec vitae dolor. Nullam
      tristique diam non turpis. Cras placerat accumsan nulla. Nullam rutrum. Nam
      vestibulum accumsan nisl.

  * References
  <<bibliography link>>
  bibliography:static/references.bib
  ```
</details>

4. Create bibtex file in `blog/static/references.bib`. Add below do `references.bib`.
<details>
  <summary>references.bib</summary>

  ```
  @comment{x-kbibtex-encoding=utf-8}

  @book{dominik-2010-tom7rm,
      author = "Dominik, Carsten",
      date = "2010-12",
      month = "12",
      pagetotal = "282",
      publisher = "Network Theory Ltd",
      subtitle = "Organize Your Life With GNU Emacs",
      title = "{The Org Mode 7 Reference Manual}",
      url = "https://web.archive.org/web/20160426062148/http://www.network-theory.co.uk/org/manual",
      year = "2010"
  }
  ```
</details>

5. Open `blog.org` and run export to hugo markdown compatible file (e.g. `C-c C-e H A`). See Emacs messages buffer.

6. Run server `hugo sever -D`.

7. Open server address: no posts.

<a id="org2f56df0"></a>

# Expected behavior (solution)

Find bibliography file in main org file, so that it's possible to export org subtrees to markdown files that have org-ref citations.

<a id="org2a09106"></a>

# Error stack

-   When trying to create a post with org-ref citations and exporting it for the first time (with `C-c C-e H A`).
    
        [ox-hugo] 1/ Exporting ‘citeproc-org Won't Export org-ref in Single Main Org File’ ..

-   When trying to export (not first export) a post in which was added org-ref citations.
    -   With `C-c C-e H A`
        
            [ox-hugo] 1/ Exporting ‘citeproc-org Won't Export org-ref in Single Main Org File’ ..
            citeproc-org--get-link-bib-info: No bibliography file was specified
    -   With `C-c C-e H H`
        
            [ox-hugo] Exporting ‘citeproc-org Won't Export org-ref in Single Main Org File’ ..
            org-find-olp: Invalid format operation %\
        
            Warning (:warning): Bibtex-completion couldn't find entry with key "dominik-2010-tom7rmnec".

# Other comments
This issue won't happen when using hugo/ox-hugo with separate/dedicated org files.

**Comment by andras-simonyi** [comment]
Hi, thanks for the detailed report! I intend to investigate this in depth and find the optimal solution, but perhaps it's useful to record here a possible quick workaround: you can also specify the bibliography to be used by setting the variable `org-ref-default-bibliography` along the lines of 

    (setq org-ref-default-bibliography '("/path/to/references.bib"))

I think this should work for single org-file ox-hugo setups as well.

**Comment by lailamor** [comment]
> specify the bibliography to be used by setting the variable `org-ref-default-bibliography`

Setting the variable works indeed. Thank you!

Seems like another issue: setting a CSL style (in this case the unique [ISO-690 (numeric, English)](https://www.zotero.org/styles/iso690-numeric-en)) with `#+CSL_STYLE: /path/to/csl_style_file` won't work.

**Comment by andras-simonyi** [comment]
Well, in a similar manner you can try to set the variable `citeproc-org-default-style-file` to the path of the desired CSL style as a workaround, but I'll try to address this issue in a more general way shortly.

**Comment by andras-simonyi** [comment]
I've committed now a small change (8b93118), which should fix this issue -- hopefully it will appear as an update in MELPA soon.

**Comment by lailamor** [comment]
I've updated to the commit
```
citeproc-el                0.1.2-2-g0ad1f97           0   0 ~/.emacs.d/straight/repos/citeproc-el/
citeproc-org               0.2.4-24-g8b93118          0   0 ~/.emacs.d/straight/repos/citeproc-org/
```
but the issue persists. Although now i only get this in the `Messages` buffer
```
[ox-hugo] 1/ Exporting ‘citeproc-org Won't Export org-ref in Single Main Org File’ ..
if: No bibliography file was specified
```
If it's of relevance, I'm using Emacs 28 (commit 9d011397).

**Comment by andras-simonyi** [comment]
Thanks, I've made another small update (22a759c) could you check again?

**Comment by lailamor** [comment]
Perfect! Now it's finding the bibliography file as well setting the csl file with `#+csl_style`. Thanks!

--------
Not sure if it's a citeproc-org issue or ox-hugo, but now, with org-ref references being used, headings are being exported as unordered lists to markdown, and being rendered as such on html.
<details>
  <summary>blog.org</summary>

  ```
#+author: Me

#+startup: content

#+hugo_base_dir: .
#+hugo_auto_set_lastmod: t


* Posts                                                                :post:
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: posts
  :END:

** Issue                                                             :@issue:

*** DONE citeproc-org Won't Export org-ref in Single Main Org File :citeproc:org:
    CLOSED: [2020-09-14 Mon 02:08]
    :PROPERTIES:
    :EXPORT_DATE: 2020-09-14
    :EXPORT_FILE_NAME: citeproc-wont-reference-single-main-org-file
    :END:

**** Here should be a heading
     Lorem cite:dominik-2010-tom7rm,dominik-2010-tom7rm ipsum dolor sit amet, consectetuer adipiscing
     elit. Donec hendrerit tempor tellus. Donec pretium posuere tellus. Proin
     quam nisl, tincidunt et, mattis eget, convallis nec, purus. Cum sociis
     natoque penatibus et magnis dis parturient montes, nascetur ridiculus
     mus. Nulla posuere. Donec vitae dolor. Nullam tristique diam non
     turpis. Cras placerat accumsan nulla. Nullam rutrum. Nam vestibulum accumsan
     nisl.

**** This here should be a heading as well
     You see, the above should be a heading, but it's being exported as
     unordered list in markdown when there's org-ref citations.

***** This should be a subheading
      A the above should be a subheading.

* References
  <<bibliography link>>
  bibliography:static/references.bib
  ```
</details>

<details>
  <summary>blog/content/posts/citeproc-wont-reference-single-main-org-file.md</summary>

  ```
+++
title = "citeproc-org Won't Export org-ref in Single Main Org File"
author = ["Me"]
date = 2020-09-14T02:08:00-03:00
lastmod = 2020-09-15T18:00:02-03:00
tags = ["post", "citeproc", "org"]
categories = ["issue"]
draft = false
+++

<!--list-separator-->

-  Here should be a heading

    Lorem ([Dominik 2010](#org3e83bb9), [2010](#org3e83bb9)) ipsum dolor sit amet, consectetuer adipiscing
    elit. Donec hendrerit tempor tellus. Donec pretium posuere tellus. Proin
    quam nisl, tincidunt et, mattis eget, convallis nec, purus. Cum sociis
    natoque penatibus et magnis dis parturient montes, nascetur ridiculus
    mus. Nulla posuere. Donec vitae dolor. Nullam tristique diam non
    turpis. Cras placerat accumsan nulla. Nullam rutrum. Nam vestibulum accumsan
    nisl.

<!--list-separator-->

-  This here should be a heading as well

    You see, the above should be a heading, but it's being exported as
    unordered list in markdown when there's org-ref citations.

    <!--list-separator-->

    -  This should be a subheading

        A the above should be a subheading.


## Bibliography {#bibliography}

<a id="org3e83bb9"></a>Dominik, Carsten. 2010. _The Org Mode 7 Reference Manual: Organize Your Life with GNU Emacs_. Network Theory Ltd. <https://web.archive.org/web/20160426062148/http://www.network-theory.co.uk/org/manual>.
  ```
</details>

![issue](https://user-images.githubusercontent.com/57581806/93264822-12b4cc00-f77e-11ea-93e9-e695d9242d55.png)

**Comment by andras-simonyi** [comment]
Thanks for the feedback! As for the probIem with headlines, this is probably caused by the default value of the customizable variable `citeproc-org-org-bib-header`, which is "* Bibliography\n", i.e., a first-level heading. Setting it to "**** Bibliography\n" seems to solve the problem.

**Comment by lailamor** [comment]
> citeproc-org-org-bib-header
> "**** Bibliography\n"

This solves the problem indeed. It works for making the correct headings both when using org-ref references and when not using them, at least when exporting to markdown with ox-hugo. Thanks again!

**Comment by dschaehi** [comment]
As a follow-up question: would it be possible to remove the heading number in front of the Bibliography heading when heading numbers are used? I have the following options in the org file:
`#+OPTIONS: h:3 toc:nil num:2 tags:nil todo:nil ':t ^:{} tasks:nil stat:nil`
I tried to add the unnumbered property (cf. https://orgmode.org/manual/Export-Settings.html) by adding 
`(setq citeproc-org-org-bib-header "*** References\n:PROPERTIES:\n:UNNUMBERED: t\n:END:")`
before calling `(citeproc-org-setup)` but was not successful. Removing the number from an arbitrary heading however works with `ox-hugo`:
```
* test
:PROPERTIES:
:UNNUMBERED: t
:END:
```
Thank you by the way for the useful package!

**Comment by andras-simonyi** [comment]
Hello, thanks for the question and sorry for reacting only now. I tried to reproduce the problem but could not  -- in theory, there should not be any difference between a manually inserted heading and the same heading inserted by citeproc-org on the basis of the `citeproc-org-org-bib-header` variable's content. In fact, I didn't see any difference with the backends I tried. Could you perhaps describe in detail what you experienced precisely when you were "not successful"?
BTW, this might be just an insignificant typo, but your line
```emacs
(setq citeproc-org-org-bib-header "*** References\n:PROPERTIES:\n:UNNUMBERED: t\n:END:")
```
is not entirely correct because an ending "\n" is missing from the string after "END:".

**Comment by dschaehi** [comment]
Oh you are right. It was the missing "\n" that caused the problem. Thanks for the hint!
